/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_NativeLibrary */

#ifndef _Included_org_example_NativeLibrary
#define _Included_org_example_NativeLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_NativeLibrary
 * Method:    validateEmail
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_example_NativeLibrary_validateEmail
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_example_NativeLibrary
 * Method:    validateUserId
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_example_NativeLibrary_validateUserId
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_example_NativeLibrary
 * Method:    logMessage
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_example_NativeLibrary_logMessage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_example_NativeLibrary
 * Method:    generateUniqueID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_example_NativeLibrary_generateUniqueID
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
